### ISSUE TITLE
RS3 equipment interface broken

### ISSUE THREAD

**Issue by tyb51** [RuneMate/Issues#13]
**Describe the bug:**
Interacting with the equipment interface is broken as it is not being recognized. The client throws the following error. 
>SEVERE ActionWindow#WORN_EQUIPMENT.getTab()'s query did not have 1 result, but instead had 0 []

**Affected game modes:** 
RS3.

**RuneMate version:** 
2.59.9

**To Reproduce Steps to reproduce the behaviour:**

Try and print out:
ActionWindow.WORN_EQUIPMENT.getTab()

**Expected behaviour:**
It throws null.
NOTE: Retrieving the worn items as sprite items doesn't seem to be an issue

**Comment by ccarpenter04** [comment]
Did they change the sprite? on the tab or anything similar?

**Comment by ccarpenter04** [comment]
Also is this in modern or legacy interface mode.

**Comment by tyb51** [comment]
Modern interface

**Comment by ccarpenter04** [comment]
Fixed in next release.
