### ISSUE TITLE
RS3: Fix Quest hub bank

### ISSUE THREAD

**Issue by tyb51** [RuneMate/Issues#21]
**Describe the bug**
Web- Landmark trying to use quest bank when it is not unlocked. 

**Affected game modes:**
RS3.

**RuneMate version:**
2.95.12

**To Reproduce**
Use Landmark to bank on an account which does not have the bank unlocked. 

**Expected behaviour**
It will always use Quest-Hub due to being close to Lodestone regardless of the unlock. 

**Additional context**
Bank chest coordinate: 3205, 3369, 0
Bank chest reward path varbit 42073: minimum value for unlock >=125
Possibly: varbit 42063 with a value of 1 for the chest to be unlocked (not sure)

**Comment by ccarpenter04** [comment]
Fixed in next web update.
