### ISSUE TITLE
Add GameObject spotAnimations to API

### ISSUE THREAD

**Issue by tyb51** [RuneMate/Issues#22]
**Is your feature request related to a problem? Please describe.**
The ability to detect spotanimations or particles is necessary for activities like questing, safe-cracking, charm hunting and PvM.

**Describe the solution you'd like**
Implement a hook to get spot animations on GameObjects.

**Describe alternatives you've considered**
In some cases particles/animations are liked to sound. But in RS3 these are broken cfr. other issue report and probably a more resource heavy calculation.

**Comment by ccarpenter04** [comment]
I believe this is referring to graphic objects (named by others). I'll consider adding them in the coming days.

**Comment by Proxify** [comment]
Another use case would be detecting the glowing rocks in the new RS3 Mining Revamp.
https://i.imgur.com/HjTTYnn.png

To my knowledge there's no other way to check if a rock is in this 'glowing' state.

**Comment by ccarpenter04** [comment]
Support for this was added in V2.96.2 with some additional information about them being posted which I feel is relevant to anyone reading this, so I'm going to go ahead and copy and paste the changelog here.

"2.96.2 is now available @here
After spending some time playing with the mechanics of the skill rework on RS3 and listening to developers, I've gone ahead and *added GameObject.getSpotAnimationId() support*. Using this method you can detect Rockertunities (@Zinl), the flashes that occur during safe cracking (@aria), and other things that almost nobody has even attempted to write a bot for such as some of the effects used while attempting to defeat "Telos, the Warden" (@auxi).

--- More Information ---
Spot animations are a special type of animation that has been supported for Players and Npcs for quite some time, however the way that the RS3 engine handles them is considerably different when it comes to GameObjects. Spot animations are unique in that they have their own unique mesh/model that is independent of the entity they appear to be associated with. In fact, the engine treats them as independent scene entities. As a result, it's possible that there will be a few edge cases where the spot animation will not be correctly detected on the GameObject that it's thought to correspond with. I have not personally seen any issues with a GameObject incorrectly reporting it's spot animation, however if you do please make an issue at github.com/runemate/issues with a full breakdown of the situation."
