### ISSUE TITLE
RS3: Add banker at Fight Cave

### ISSUE THREAD

**Issue by tyb51** [RuneMate/Issues#23]
**Is your feature request related to a problem? Please describe.**
This banker is not included in the landmarks.

**Describe the solution you'd like**
Add the banker NPC with name "TzHaar-Mej-Jal" with action "Bank" located within a 5 (probably less) radius of Coordinate(4612, 5131, 0)

**Describe alternatives you've considered**
/

**Additional context**
This bank could be useful in addition to implementing the "TokKul-Zo (Charged)" ring for quick banking and fairy ring access.

**Comment by ccarpenter04** [comment]
Added in the next web update, please create a separate issue for "TokKul-Zo (Charged)"
