### ISSUE TITLE
RS3 Menaphos VIP skilling area bank chest: add requirement to web

### ISSUE THREAD

**Issue by tyb51** [RuneMate/Issues#27]
**Describe the bug**
Web/Landmarks will use the VIP resource area in Menaphos as a bank when it is not accessible 

**Affected game modes:**
RS3.

**RuneMate version:**
2.95.14

**To Reproduce**
Use landmarks to bank near the VIP skilling area.

**Expected behaviour**
Spam clicks the chest, but cannot enter the area

**Additional context**
Solution:
The bank chest: Bank chest at Coordinate(3182,2741,0)

The requirement:
VarpRequirement 7002: Value > 1419000

**Comment by tyb51** [comment]
The varp represents the actual number of points you have (atleast multiied by 10 due to having 1 decinal in game). There could be a varbit with the unlocked stage of unlocks, but I cannot provide that

**Comment by ccarpenter04** [comment]
This is really an issue with the VIP archway it sounds like

**Comment by ccarpenter04** [comment]
Bank is blacklisted for a while because reachability issues would impair path traversal even if the archway gets supported.
