### ISSUE TITLE
The login screen world selector consistently picks the wrong world on OSRS

### ISSUE THREAD

**Issue by ccarpenter04** [RuneMate/Issues#3]
**Describe the bug**
When the login handler needs to change to a different world, such as if the default world is P2P and the users account is F2P, it opens the world selector but often either doesn't click or clicks the wrong world and then repeats itself. Changing worlds from the in game world selector works fine.

**Affected game modes:**
OSRS.

**RuneMate version:**
2.90.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to start a bot while completely logged out with a F2P account with a default P2P world selected.
2. Observe the mentioned behavior.

**Expected behaviour**
The login handler to select the correct (desired) world on the first try.

**Additional context**
Often breaks as a result of Jagex changing the amount of available worlds.

**Comment by aidden93** [comment]
Reproduced on 2.92.4.
Said it was switching to world 451 but selected 519.

`00:00:25 TRACE	[Login handler] Switching worlds to 451
00:00:25 DEBUG	Opening world at world select index 132
00:00:25 DEBUG	Clicking world 451 at the bounding rectangle of InteractableRectangle(716, 310, 82, 12)
00:00:26 DEBUG	Successfully clicked within InteractableRectangle(716, 310, 82, 12)`

**Comment by ccarpenter04** [comment]
Should be resolved in the next update
https://i.gyazo.com/4607dd55f7b94a6cf667809f890b5cab.mp4

**Comment by ccarpenter04** [comment]
This was resolved in 2.94.0
