### ISSUE TITLE
WorldHop Changes

### ISSUE THREAD

**Issue by Snufalufugus** [RuneMate/Issues#39]
**Is your feature request related to a problem? Please describe.**
It's easy for an author to use WorldHop.hopToRandom(true) with the false assumption that it will take world limitations into account.  In addition, each author has to go back and modify whatever they use whenever a new type of world is added, rather than the update being made to the API.

Also, I think WorldHop.hopTo() doesn't handle opening the world hop interfacewindow like the rest of the API does.

And it's annoying to have to check each skill total value.

**Describe the solution you'd like**
A new method of hopToRandomUseable() that would look like this:
WorldHop.hopToRandom(worldOverview -> worldOverview.isMembersOnly() && !worldOverview.isPVP() && !worldOverview.isDeadman() && !worldOverview.isTournament() && !worldOverview.isSkillTotal500() && !worldOverview.isSkillTotal750() && !worldOverview.isSkillTotal1250() && !worldOverview.isSkillTotal1500() && !worldOverview.isSkillTotal1750() && !worldOverview.isSkillTotal2000() && !worldOverview.isSkillTotal2200() && !worldOverview.isSkillTotal2600());
            
If the API really doesn't open the window already, change it to do so to be consistent with everything else.

It would also be nice to just get a worldOverview.isSkillTotalRestricted()

**Describe alternatives you've considered**
Making each author implement this individually.

**Additional context**
:)

**Comment by ccarpenter04** [comment]
It already does take various factors into account.

**Comment by ccarpenter04** [comment]
RS3 or OSRS

**Comment by ccarpenter04** [comment]
Perhaps some of the more recent additions haven't been blacklisted, which issues have you encountered?

**Comment by ccarpenter04** [comment]
It looks like it wasn't factoring in  skill total 500, 750, or 2600 for P2P and several more for F2P

**Comment by Snufalufugus** [comment]
OSRS.  I haven't encountered any issues recently, but the JDocs didn't mention any world filtering, nor did I see any in IntelliJ's decompiled code.

**Comment by ccarpenter04** [comment]
Could you check it again after 2.95.20?
