### ISSUE TITLE
Have #hover() instantly return true when it's already hovering.

### ISSUE THREAD

**Issue by RobinPC** [RuneMate/Issues#40]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Have #hover() instantly return true when it is already hovering the entity. The documentation states: "returns true if the mouse is hovering the entity", however, the mouse keeps moving over the entity.

**Describe alternatives you've considered**

**Additional context**
Currently only tested for Sprite Items.

**Comment by Defeat3d** [comment]
Same happens to GameObjects as I've experienced with my hunter. I think I've seen it happen to Npc's too but not 100% sure.

Agree with the solution.

**Comment by RobinPC** [comment]
An additional solution can be to only move the mouse slightly around the first 'hovered' point. The current behavior is quite extreme and inhuman.

**Comment by ccarpenter04** [comment]
The documentation is more likely to be revised than this

**Comment by RobinPC** [comment]
This doesn't solve the problem, though. The current behavior of hover() is really inhuman. I have never seen any player move their mouse like this when hovering something:
https://i.imgur.com/P2aQId5.gifv

**Comment by ccarpenter04** [comment]
It's not meant to track the entity while moving, that's a simple task that an author can write themselves. Take the bounding model and project it's centroid and track that.

**Comment by RobinPC** [comment]
Same can be said for the hover() function itself though, but that's also in the API. Don't want to sound rude, but this can be said for a lot of things that are already in the API.
This suggestion doesn't add any boilerplate code and only has a positive effect on its behavior.

**Comment by Defeat3d** [comment]
It doesn't really need to "track", just check for the mouse to be within the target's bounds, and hover the target if it's not.

This can be done by the authors themselves though.

**Comment by ccarpenter04** [comment]
It would break all mouse implementations as the rely on it's current behavior.
