### ISSUE TITLE
New Treasure Hunter widget not detected

### ISSUE THREAD

**Issue by aidden93** [RuneMate/Issues#41]
**Describe the bug**
Interface closer no longer closes the treasure hunter widget

**Affected game modes:**
RS3.

**RuneMate version:**
2.95.18

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a bot on an account that has at least one key and is logged out or hasn't closed the widget

*Please include the code used to produce this bug.*

**Expected behaviour**
It should automatically close it via the x icon

**Screenshots**
![image](https://user-images.githubusercontent.com/3121589/50773361-c6e12c80-12e4-11e9-9057-407573f981f7.png)

**Additional context**

**Comment by RobinPC** [comment]
I fully expected Aidden to provide this, but the new interface query for this interface is:
Interfaces.newQuery().types(InterfaceComponent.Type.CONTAINER).containers(1252).visible().actions("Select").results();

With action "Select" to close it.

**Comment by aidden93** [comment]
Sorry, was in a hurry. It's well past my bed time lol.

On 8 Jan 2019 1:38 am, Robin <notifications@github.com> wrote:

I fully expected Aidden to provide this, but the new interface query for this interface is:
Interfaces.newQuery().types(InterfaceComponent.Type.CONTAINER).containers(1252).visible().actions("Select").results();

With action "Select" to close it.

**Comment by ccarpenter04** [comment]
Fixed
