### ISSUE TITLE
MoneyPouchListener onContentsChange event not firing

### ISSUE THREAD

**Issue by rossity** [RuneMate/Issues#43]
**Describe the bug**
Title, when adding or removing money from money pouch, the listener event is never fired. InventoryListener is working fine however (so I don't believe it's an implementation issue).

**Affected game modes:**
RS3

**RuneMate version:**
2.96.0

**To Reproduce**
Steps to reproduce the behaviour:
Add or remove money from money pouch.

*Please include the code used to produce this bug.*
```
@Override
    public void onContentsChanged(MoneyPouchEvent moneyPouchEvent) {
        System.out.println(moneyPouchEvent);
    }
```

**Comment by ccarpenter04** [comment]
Was probably always the case
