### ISSUE TITLE
Web Wizard's Tower Basement

### ISSUE THREAD

**Issue by simwij** [RuneMate/Issues#50]
**Describe the bug**
The web does not seem to support walking into the basement of the Wizard's tower. It is required for the Rune Mysteries quest.

**Affected game modes:**
OSRS (have not tested rs3)

**RuneMate version:**
 2.96.3

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a web path to the coordinate (3103, 9573, 0) (it is down the basement at Sedridor, see ss)
2. Path is null

*Please include the code used to produce this bug.*
```
// Kotlin
val webPath = Traversal.getDefaultWeb().pathBuilder.buildTo(Coordinate(3103, 9573, 0))  
assert(webPath != null)
```

**Expected behaviour**
Ability to walk down the basement, and especially to the Wizard Sedridor

**Screenshots**
**Scroll down for the items in text so you don't have to write from the images.**
![webaddition 1](https://user-images.githubusercontent.com/1533312/51088569-99233a00-1761-11e9-8d63-3a102a6e069d.png)
![webaddition 2](https://user-images.githubusercontent.com/1533312/51088570-99233a00-1761-11e9-9295-7a44989ea576.png)
![webaddition 3](https://user-images.githubusercontent.com/1533312/51088571-99233a00-1761-11e9-854c-cb958254cafa.png)
![webaddition 4](https://user-images.githubusercontent.com/1533312/51088572-99bbd080-1761-11e9-9c38-009be89d2833.png)

Objects in order:
Ladder to the basement 
Coord: Coordinate(3104,3162,0)
Action: Climb-down
Type: Primary

Ladder up from the basement:
Coord: Coordinate(3103, 9576, 0)
Action: Climb-up
Type: Primary

Door to Sedridor when closed:
Coord: Coordinate(3108,9570,0)
Action: Open
Type: Boundary

Door to sedridor when open probably not needed, but is the last screenshot.

**Comment by ccarpenter04** [comment]
I think what may actually be needed is some hardcoded data for the two doors in the tower since they don't seem to be being found by the heuristic.

**Comment by simwij** [comment]
Well shame on me, the doors actually works. So never mind that. Then the ladder is all that needs adding :D

**Comment by ccarpenter04** [comment]
The web should start to successfully generate a path down there shortly, in addition the models orientation have been fixed in the next client update (just something I noticed in your screenshots).

**Comment by simwij** [comment]
Yes, it now navigates down there. Good job!
