### ISSUE TITLE
Add Sandicrahb to the web

### ISSUE THREAD

**Issue by RobinPC** [RuneMate/Issues#51]
**Describe the solution you'd like**
Add support for the 'Sandicrahb' NPC to the web so we can build web paths to the [Crabclaw Isle](http://oldschoolrunescape.wikia.com/wiki/Crabclaw_Isle). In order to travel there, you need to pay 10.000 coins to '[Sandicrahb](http://oldschoolrunescape.wikia.com/wiki/Sandicrahb)' who is located on Zeah Shore. It is instant travel and can be set in motion by interacting with him using the "Travel" option.
https://i.imgur.com/Z8jJEEk.png

Sandicrahb is located on Zeah shore. His roaming coordinates are:
`Coordinate(1783, 3458, 0)` `Coordinate(1782, 3458, 0)` `Coordinate(1781, 3458, 0)` `Coordinate(1782, 3459, 0)` `Coordinate(1781, 3459, 0)` `Coordinate(1782, 3459, 0)` `Coordinate(1782, 3457, 0)` `Coordinate(1783, 3457, 0)` `Coordinate(1781, 3458, 0)`
Minimap location: https://i.imgur.com/Gd0m6DD.png

To get back to the main island, you can simply talk to him again. He can be found on the island itself as well, on `Coordinate(1779, 3418, 0)`. Traveling back requires no payment.

**Comment by ccarpenter04** [comment]
Does he move at all when he's on Crabclaw Isle?

**Comment by RobinPC** [comment]
The NPC does **not** move when he's on Crabclaw Isle.
As for the roaming area: `Coordinate(1783, 3458, 0)` (center) with a radius of 5 would suffice.

Also, whenever you pay Sandricrahb, the screen will fade out to a black screen, and then fade back in. And it'll say: **"You pay Sandicrahb 10,000 coins and depart for Crabclaw Isle."**. Thought that was worth a mention.

**Comment by ccarpenter04** [comment]
What coordinate do you land on when traveling via him each way?

**Comment by RobinPC** [comment]
If you go to Crabclaw Isle, you end up on `Coordinate(1778, 3417, 0)` and if you go back to the mainland, you will end up on: `Coordinate(1784, 3458, 0)`

**Comment by ccarpenter04** [comment]
Implemented
