### ISSUE TITLE
Web Enhancement - Shantay Pass

### ISSUE THREAD

**Issue by NoahQuinnCentrica** [RuneMate/Issues#54]
**Is your feature request related to a problem? Please describe.**
When attempting to enter the desert in RS3, a warning pops up asking you to confirm whether or not you want to enter. The web currently does not support this and attempts to walk straight past it.

**Describe the solution you'd like**
Interaction with the Shantay Pass.

**Describe alternatives you've considered**
Teleport scrolls and manual traversal.

**Additional context**
Interface details:
![image](https://user-images.githubusercontent.com/39404120/51200254-e2ee5a80-18f0-11e9-9e65-8e78a66c37b9.png)
Starting Coordinate(s): 3305, 3117, 0 and 3303, 3117, 0.
Ending Coordinate(s): 3305, 3115, 0 and 3303 3115, 0.

Shantay Pass object details:
![image](https://user-images.githubusercontent.com/39404120/51200519-a53e0180-18f1-11e9-82d8-11894836a501.png)
![image](https://user-images.githubusercontent.com/39404120/51200570-ce5e9200-18f1-11e9-8ddb-6b17a140355c.png)

**Comment by ccarpenter04** [comment]
It's actually supposed to be handled by the client's interface closer. You aren't disabling it by any chance are you?

**Comment by NoahQuinnCentrica** [comment]
My bot was disabling the interface detection thus making this issue resolved.
