### ISSUE TITLE
Implement Karamja log to web

### ISSUE THREAD

**Issue by DerkSchooltink** [RuneMate/Issues#58]
Walk from Karamja lodestone to the log balance:

![image](https://user-images.githubusercontent.com/22047701/51406996-03b9e880-1b5b-11e9-8c89-6940e9eeda3b.png)

Information about obstacle:

![image](https://user-images.githubusercontent.com/22047701/51407108-411e7600-1b5b-11e9-9ffd-5893c7ba415b.png)

Level needed: TBD

**Comment by ccarpenter04** [comment]
Implemented
